version: '3'
services:
 azkaban-mysql:
  container_name: "azkaban-mysql"
  image: mysql:5.6
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: "Root@123"
  ports:
  - "3307:3306"
  volumes:
  - ./mysql/data:/var/lib/mysql
  - ./mysql/conf:/etc/mysql
  networks:
  - azkaban

 executor:
    image: hhx7/azkaban-executor
    container_name:   executor
    hostname: executor
    restart: always
    ports:
      - "12321:12321"
        # depends_on:
        #   - mysql
        # command: /app/bin/start-exec.sh
    volumes:
      #- ./azkaban/azkaban-executor/bin:/app/bin
      - ./azkaban/azkaban-executor/conf:/app/conf
      - ./azkaban/azkaban-executor/log:/app/log
    links:
      - azkaban-mysql
    networks:
      - azkaban

 webserver:
      image: hhx7/azkaban-webserver
      container_name: webserver
      hostname: webserver
      restart: always
      depends_on:
        # - mysql
        - executor
      ports:
          - "8099:8081"
      # command: /app/bin/start-web.sh
      volumes:
          - ./azkaban/azkaban-webserver/bin:/app/bin
          - ./azkaban/azkaban-webserver/conf:/app/conf
          - ./azkaban/azkaban-webserver/log:/app/log
      entrypoint: ./bin/run.sh
      links:
          - executor
          - azkaban-mysql
      networks:
          - azkaban
          
networks:
  azkaban:
    driver: bridge
